DELETE http://localhost:3000/api/blogs/abcd
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJ1c2VybmFtZTFAZ21haWwuY29tIiwibmFtZSI6Im5hbWUxIiwiaWF0IjoxNjU2OTQ1Njg2LCJleHAiOjE2NTcyMDQ4ODZ9._dKrkn_DLxN5y8Kyi2PUEIvdbsaWY8Cx3crDMj-4jHc

###

DELETE http://localhost:3000/api/blogs/1000
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJ1c2VybmFtZTFAZ21haWwuY29tIiwibmFtZSI6Im5hbWUxIiwiaWF0IjoxNjU2OTQ1Njg2LCJleHAiOjE2NTcyMDQ4ODZ9._dKrkn_DLxN5y8Kyi2PUEIvdbsaWY8Cx3crDMj-4jHc

###

DELETE http://localhost:3000/api/blogs/16
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJ1c2VybmFtZTFAZ21haWwuY29tIiwibmFtZSI6Im5hbWUxIiwiaWF0IjoxNjU2OTQ1Njg2LCJleHAiOjE2NTcyMDQ4ODZ9._dKrkn_DLxN5y8Kyi2PUEIvdbsaWY8Cx3crDMj-4jHc
