PUT http://localhost:3000/api/users/abcd
Content-Type: application/json

{

}

###

PUT http://localhost:3000/api/users/abcd
Content-Type: application/json

{
  "name": "name1new"
}

###

PUT http://localhost:3000/api/users/username1
Content-Type: application/json

{
  "name": "name1new"
}